version: '3.9'

services:
  imdb:
    build:
      context: .
    restart: on-failure
    command: npm start
    ports:
        - "3000:3000"
    volumes:
        - ./app/:/app/
        - /app/node_modules
 
